### PR TITLE
Update travis-config to latest version

### PR DESCRIPTION
**Pull request by bnferguson**
Fixing some of the same issues that came up in https://github.com/travis-ci/travis-listener/pull/16 and others. 

Since `travis-config` is still on the `0.1.X` version instead of `1.X.X` version in this project it felt like a good time to get it in line with other projects that have a direct dependency with `travis-config` (as opposed to `travis-core`). 

Once this gets into master, I'll be looking at creating a backport for Enterprise 2.0. 👍

### CODE REVIEW

File: lib/travis/logs/config.rb [hunk 1]
```diff
@@ -8,7 +8,7 @@ class Config < Travis::Config
              logs_database: { adapter: 'postgresql', database: "travis_logs_#{Travis.env}", encoding: 'unicode', min_messages: 'warning' },
              s3:            { hostname: 'archive.travis-ci.org', access_key_id: '', secret_access_key: '', acl: :public_read },
              pusher:        { app_id: 'app-id', key: 'key', secret: 'secret', secure: false },
-             sidekiq:       { namespace: 'sidekiq', pool_size: 3 },
+             sidekiq:       { namespace: 'sidekiq', pool_size: 22 },
```
Comment (henrikhodne) [inline lib/travis/logs/config.rb]: What is this the pool size for? 3→22 seems like quite a high increase.

Comment (bnferguson) [inline lib/travis/logs/config.rb]: It is a big jump. It turns out that in staging it's not been able to start up for some time because the `pool_size` required for the concurrency we pass it is anywhere from 7 to 22 (concurrency is set to 20 and then + 2) and it defaults to 3. As I understand it, we set a lot of these in production via config values. But in Staging they weren't set. Once I get this PR to actually succeed, I'll probably split this change out into a separate PR since it's worth noting.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
I'm seeing a lot of deps being downgraded as a result of this.

**Comment by bnferguson** [comment]
> I'm seeing a lot of deps being downgraded as a result of this.

Eep. Good :eye:. Should just be `travis-config` and `hashr` Looks like the rebundle off of the merge conflict is giving me the business. Fixing.

**Comment by bnferguson** [comment]
@igorwwwwwwwwwwwwwwwwwwww - OK, should be fixed with https://github.com/travis-ci/travis-logs/pull/45/commits/775c4407a8785d413bdb27656503da3eb8569686 

Really glad you caught that! 🙌

**Comment by bnferguson** [comment]
I'm getting some pretty bizarre spec failures in this. Bounced off of them yesterday but getting master builds work in Enterprise is already a week behind, so if anyone has time to take a look that would be amazing. I'm probably missing something fairly obvious. Also I'm not sure what I did in https://github.com/travis-ci/travis-logs/pull/45/commits/e275aaf515e3a93164994f6e6b792dd727817893 was a good approach even if it did make a couple spec failures better. 

Also there's this whole `Travis::Logs.config` vs `Travis.config` thing going on (`Travis.config` just points at `Travis::Logs.config`, but I'm wondering if when dealing with stubbing out responses it's causing issues). 

Also https://github.com/travis-ci/travis-config/pull/9 needs to be pulled in for this to work in HA setups where the amqps protocol is used, which also needs some review before I merge it.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Added some hacks, it's passing now! :)

**Comment by bnferguson** [comment]
> Added some hacks, it's passing now! :)

YESSSSSS. Thanks so much for doing this. Deploying to staging now. 🚢

**Comment by bnferguson** [comment]
This is currently crashing in staging due to some `travis-support` and `Hashr` issues. As mentioned in slack: 

> New dev question of the day! How actively is `travis-support` being used by other projects? Is this something that's deprecated or still being used. Big question is that while tracking down the errors in `travis-logs` after updating `travis-config` the new behavior of Hashr (where it nolonger is a type of Hash so hash functions return `nil`. breaks the AMQP support. You can see this here: https://github.com/travis-ci/travis-support/blob/master/lib/travis/support/amqp/march_hare/consumer.rb#L23 leading to https://github.com/travis-ci/travis-support/blob/master/lib/travis/support/amqp/march_hare/consumer.rb#L54-L56 returning `nil`.

This will need to be fixed in order to move on with this PR, for the ends of getting master building for Enterprise, I may just need to port some of the changes done in the Enterprise 2.0 branch and move on until we can come back to fixing this issue. Exploring that now as I'm already 2-3 levels deep into this yak shave. 

Oh yes, and the error in logs itself looks like: 

```
› ./bin/receive_logs
I ** Starting Log Parts Processor **
I Starting metriks reporter librato.
I No metriks reporter configured.
D [consumer] subscribing to "reporting.jobs.logs" with nil
NoMethodError: undefined method `[]' for nil:NilClass
  build_consumer at /Users/bnferguson/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/march_hare-2.21.0-java/lib/march_hare/queue.rb:158
       subscribe at /Users/bnferguson/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/march_hare-2.21.0-java/lib/march_hare/queue.rb:179
       subscribe at /Users/bnferguson/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/bundler/gems/travis-support-2cd02d2a06fd/lib/travis/support/amqp/march_hare/consumer.rb:29
       subscribe at /Users/bnferguson/dev/travis-logs/lib/travis/logs/receive/queue.rb:25
       subscribe at /Users/bnferguson/dev/travis-logs/lib/travis/logs/receive/queue.rb:14
    block in run at /Users/bnferguson/dev/travis-logs/lib/travis/logs/receive.rb:30
            upto at org/jruby/RubyInteger.java:134
             run at /Users/bnferguson/dev/travis-logs/lib/travis/logs/receive.rb:29
          <main> at ./bin/receive_logs:10```

**Comment by bnferguson** [comment]
Naturally as soon as I write that, I realize we 

1. Already have the newest `travis-config` working in `enterprise-2.0` 
2. The reason that works is because we don't use `travis/support/amqp` anymore but instead use the `travis/amqp` gem which has been corrected for the issues I've pointed out. :tada: 

This is now working locally. Will get on about testing in it staging and getting it out later tonight.
